#! /bin/bash
set -E
trap 'trap - ERR; echo "$0: error in $BASH_COMMAND on line $LINENO" >&2; exit 1' ERR
trap 'trap - 0; eval "$CLEANUP"' INT TERM EXIT

# prevent errors in "printf"
export LC_ALL=C LC_NUMERIC=C
CLEANUP=:
ME=$(basename "$0")

TMPD=$(mktemp -d /tmp/rules.XXXXXX)
RULESD=/tmp/test_scsi_rules
CLEANUP="rm -rf $TMPD;$CLEANUP"


COMMIT=last-scsi_id
SG3_COMMIT=suse-udev-rules
SG3_REPO=mwilck
SYSTEMD_GIT=https://raw.githubusercontent.com/mwilck/systemd-1/$COMMIT/rules
SG3_GIT=https://raw.githubusercontent.com/$SG3_REPO/sg3_utils/$SG3_COMMIT/scripts

SHA1SUMS="\
d599d0c6bdcb20a02278afdc84fc59209ebbbc30  53-storage-hardware.rules
1053d093e759132ce7b51aeec324abb3904d8be3  54-before-scsi-sg3_id.rules
91e9ed529c5adaa4cd802e0f76357d35488a058e  55-scsi-sg3_id.rules
9582c6924cd00d5443a2b694a6220ab3c460c683  55-zz-scsi_id.rules
9952600a396efc6baa5fd2aebc418355270c1f42  58-cdrom_id.rules
3592110f20a8b288b0f541030e498add4aa772dc  59-storage-content.rules
2e97f1445b5a0e45ef10fd7660097cb156aa4d94  60-persistent-storage.rules
0dc0396a818bfa47d581dd1394311acfe2186f69  60-persistent-storage-tape.rules"

UDEV_RULES="55-zz-scsi_id.rules 53-storage-hardware.rules \
58-cdrom_id.rules 59-storage-content.rules \
60-persistent-storage.rules 60-persistent-storage-tape.rules"
SG3_RULES="55-scsi-sg3_id.rules 54-before-scsi-sg3_id.rules"
ALL_RULES="$UDEV_RULES $SG3_RULES 60-cdrom_id.rules"

# These rules are present on some SUSE distros to provide backward
# compatibility towards older releases.
# For the purpose of this test, they generate artefacts.
COMPAT_RULES="61-persistent-storage-compat.rules 59-scsi-cciss_id.rules"

check_reqs() {
    local p
    for p in systemctl udevadm curl tar sha1sum sg_inq; do
	type $p &>/dev/null || {
	    echo "program \"$p\" not found, please install it first" >&2
	    exit 1
	}
    done
}

fetch_rules() {
    local f r
    pushd "$RULESD" >/dev/null
    sha1sum -c <<<"$SHA1SUMS" &>/dev/null && return 0
    echo "$ME: fetching rules from github" >&2
    for f in $UDEV_RULES; do
	curl -s -o "$f" "$SYSTEMD_GIT/$f"
    done
    for f in $SG3_RULES; do
	curl -s -o "$f" "$SG3_GIT/$f"
    done
    >60-cdrom_id.rules
    cat >10-test-scsi.rules <<EOF
SUBSYSTEMS=="scsi", ENV{ID_SCSI_INQUIRY}="0"
EOF
    sha1sum -c <<<"$SHA1SUMS"
    r=$?
    popd >/dev/null
    return $r
}

check_etc_rulesd() {
    local f
    for f in $ALL_RULES 10-test-scsi.rules 55-storage-hardware.rules \
			58-scsi-sg3_symlink.rules \
			$COMPAT_RULES; do
	# Don't overwrite any existing system rules
	[[ ! -e "/etc/udev/rules.d/$f" ]] || {
	    echo "/etc/udev/rules.d/$f exists - aborting" >&2
	    exit 1
	}
    done
}

_disable_rules() {
    local x
    for x in "$@"; do
	>"/etc/udev/rules.d/$x"
    done
}

disable_sg3() {
    _disable_rules $SG3_RULES 58-scsi-sg3_symlink.rules
}

enable_sg3_orig() {
    _cleanup_rules $SG3_RULES 58-scsi-sg3_symlink.rules
}

disable_compat() {
    local f
    # Disable compat rules, they generate artefacts
    # This will be undone by cleanup_rules
    for f in $COMPAT_RULES; do
	>/etc/udev/rules.d/$f
    done
}

prefer_sg_inq() {
    _install_rules 10-test-scsi.rules
}

prefer_sysfs() {
    _cleanup_rules 10-test-scsi.rules
}

_install_rules() {
    local r
    for r in "$@"; do
	cp -af "$RULESD/$r" /etc/udev/rules.d
    done
}

_cleanup_rules() {
    local x
    for x in "$@"; do
	rm -f "/etc/udev/rules.d/$x"
    done
}

cleanup_rules() {
    _cleanup_rules $ALL_RULES 58-scsi-sg3_symlink.rules $COMPAT_RULES
}

get_devices() {
    pushd /sys >/dev/null
    DEVICES=($(ls -d block/cciss* block/sd*[a-z] block/sd*[a-z]/sd*[0-9] block/sr* class/scsi_tape/{n,}st*[0-9] class/scsi_generic/* class/scsi_changer/* 2>/dev/null || true))
    popd >/dev/null
}
do_test() {
    local dir=$1 dev st en tim
    echo "$ME: running test \"$1\"" >&2
    mkdir -p "$TMPD/$dir"
    pushd "$TMPD/$dir" >/dev/null
    sha1sum /usr/lib/udev/rules.d/*.rules /etc/udev/rules.d/*.rules \
	    >"$TMPD/$dir/rules.txt"
    ### DO NOT systemctl restart systemd-udevd, NOT NECESSARY.
    for dev in "${DEVICES[@]}"; do
	mkdir -p $(dirname "$dev")
    done
    st=$(date +%s.%N)
    for dev in "${DEVICES[@]}"; do
	udevadm test "/$dev" >"$dev.txt" 2>"$dev.err" || true
    done
    en=$(date +%s.%N)
    tim=$(echo $en $st - p | dc)
    printf "$ME: test \"$1\" took %.2f s\\n" $tim >&2
    popd >/dev/null
}

[[ -d "$RULESD" ]] || mkdir "$RULESD"

check_reqs
check_etc_rulesd
fetch_rules

CLEANUP='cleanup_rules;'"$CLEANUP"

disable_compat

get_devices
[[ ${#DEVICES[@]} -gt 0 ]] || {
    echo "$ME: no SCSI devices found" >&2
    exit 1
}
echo "$ME: ${#DEVICES[@]} SCSI devices will be checked" >&2

do_test 00-before

# sg3_utils reading sysfs inquiry attributes
_install_rules $ALL_RULES

do_test 01-sysfs

# sg3_utils calling sg_inq
prefer_sg_inq
do_test 02-inquiry
prefer_sysfs

# remove rules from systemd - simulate test just with updated
# sg3_utils
_cleanup_rules $UDEV_RULES 60-cdrom_id.rules
do_test 06-sg3-only
_install_rules $UDEV_RULES 60-cdrom_id.rules

# sg3_utils deactivated - using scsi_id
disable_sg3
do_test 03-scsi_id
enable_sg3_orig

cleanup_rules
disable_compat
disable_sg3
do_test 04-nosg3
enable_sg3_orig

rm -f "/etc/udev/rules.d/$SG3_RULES"
do_test 05-after

echo "$ME: creating result file $TMPD.tar.gz" >&2
tar cz -C /tmp -f "${TMPD}.tar.gz" "${TMPD#/tmp/}"
echo "$ME: done, thanks. Please send results to <mwilck@suse.com>" >&2
echo "$ME: run 'check-results ${TMPD}.tar.gz' to inspect" >&2
